name: charts_weebi
description: "Weebi charts"
version: 0.0.1
homepage: https://weebi.com
repository: https://github.com/weebi-com

environment:
  sdk: ">=3.3.3 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  models_weebi: ^1.1.19
  protos_weebi: ^1.2.3 # currency: firm/chain/boutique + ticket FX snapshot
  design_weebi: ^0.1.2

# dashboards & charts
  fl_chart: ^0.71.0 #^0.69.0
  pluto_grid_plus: ^8.4.3
  pluto_grid_plus_export: ^1.0.5
  pdf: ^3.11.1
  printing: ^5.13.4
  provider: ^6.1.4
  gatekeeper_weebi: any
  intl: any


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
